### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by BUMPRW** [vadim-bach/EyezOn-SmartThings-Switch#1]
This does not appear to work without Envisalerts Plus, a subscription service, since the free version does not support mobile links.  I did have a link initially, but it is gone when I was troubleshooting.

Also does not appear to support pins with a leading "0" either the Samsung app is chopping it off or it is chopped somewhere.

**Comment by yundesa** [comment]
So you don't see Generate Mobile Portal Link, under Account settings?  It should be right under Mobile app. 
If so,  I'm guessing they changed access for the mobile portal.

**Comment by BUMPRW** [comment]
I’m checking on that now, I may be wrong.  I was able to regain access to my link, but the wording is confusing on the site.  So I am in the process of adding their app to my phone.

**Comment by yundesa** [comment]
It's actually on the web site.  Login and under Account setting,  you'll see a section call Generate Mobile Portal Link,  which should be right under the section Mobile Portal.

**Comment by BUMPRW** [comment]
I got that step done initially and then it disappeared, it is back now so I’m going to retry again, but I don’t think I can get past the pin issue something is clipping my first character

**Comment by BUMPRW** [comment]
I believe it is working at some level, but I believe I have to break out the book to reprogram my pin since that appears to be the stopping point

**Comment by BUMPRW** [comment]
I added another user pin without a leading “0” and it still would not execute.  Before I did this I changed the for the type of variable to “Text” and got a system reaction but no success.  I then changed it to “####” and also got a reaction.  I then reset it back to “number” and have had no reaction.  I also found some HTTP commands that directly talk to my card that do work, so I am also playing with them

**Comment by BUMPRW** [comment]
Went back through some earlier comments and got the idea to try the EVL4 version and the ARM-Away does work, but not always consistently.  I have to run over and input a code to disarm unless I use the HTML commands I found.  ARM-STAY doesn't seem to work.  The two http commands for ARM-STAY and DISARM that I use work http://<user>:<PW>@<EVL-IP ADDR>/2?A=3&P=1&X=<PIN> and  http://<user>:<PW>@<EVL-IP ADDR>/2?A=4&P=1&X=<PIN>, respectively. I just reconfirmed the DISARM didn't work, except via the keypad or the HTML code above.

**Comment by BUMPRW** [comment]
Third attempt reinstalling EVL4 code and now it works, really didn't change anything.  On/off statuses for away and stay in Smartthings indicate "On" when the system is off, but away and stay are working now as well as motion, contact, and fire/smoke systems in Alexa.  

My system is most definitely an EVL3.  I installed it myself about 3-6 months before the EVL4 came out.  It also states it on the local web page.  I don't see the contact devices in Smartthings, but then I didn't install devices for them.

**Comment by BUMPRW** [comment]
Correction: Amazon skill is providing the sensor data.

**Comment by vadim-bach** [comment]
Thanks for the feedback. Unfortunately, based on the feedback I received from several people thus far, there seems to be two variations of requests going to the server and turns out that those are not actually a function of EnvisaLink 3 vs 4. Might be something else. For now I added a note in the installation instructions to make this clear to reduce setup churn.
