### ISSUE TITLE
issue with getting status with 2 active partitions

### ISSUE THREAD

**Issue by markojr13** [vadim-bach/EyezOn-SmartThings-Switch#2]
It appears that when getting the system status text file it looks at your entire account and not at separate partitions.
If I arm part 1 with part 2 not armed, status of the virtual switch will return to disarmed. I believe this is because the status file that is retrieved returns a ready for part 2. Part 1 will arm, but this situation denies you from disarming part 1 because switch status returns to disarmed,
With part 2 armed, virtual switch stays in correct state and everything seems to work good.
I did not try setting up partition 2 yet. Not sure if I will because it stays armed most of the time.
Is there a way to extract status file from individual partitions?
Thank you for your work on integrating eyezon.

**Comment by vadim-bach** [comment]
I pushed out an update to the code that should take care of this issue.
Give it another go and let me know if it solves the problem for you.
