### ISSUE TITLE
I have a 4 digit pin, it only accepts 3 digit pins??

### ISSUE THREAD

**Issue by fireheadman** [vadim-bach/EyezOn-SmartThings-Switch#3]
Unless I am missing something.... my 4 digit pin is greying out the save button on the ARM/DISABLE setting in smartthings for the device handler.

Any insight would be appreciated.

**Comment by vadim-bach** [comment]
That's super strange. I just tested again and it works fine with 4 digit pin. Do you have any special characters? Is there a chance you're inserting a space as the first character and not realizing it?

**Comment by fireheadman** [comment]
oddly enough, yes this works on the Classsic ST app, but if you launch the new ST app.... it does not.
I set it fine in the Classic, then it shows correctly in the new ST app.

**Comment by fireheadman** [comment]
No space.  I’ll retest a 4 character pin and screenshot

**Comment by fireheadman** [comment]
Here are the screenshots proving it will not allow a 4th number in the pin section on the new app... but it does in the classic app (which is slated to be retired by samsung)

3 digits in.... works
![image](https://user-images.githubusercontent.com/19847195/88622409-0191ed80-d060-11ea-8797-cae586a57ace.png)

4 digits in... "Save" greys out... cannot save it
(BTW:  I tried both DTH's provided)
![image](https://user-images.githubusercontent.com/19847195/88622452-1a020800-d060-11ea-8621-d29b902831f1.png)

ST Classic app... I could set the 4th digit and it saved.
But I cannot modify it in the new app
![image](https://user-images.githubusercontent.com/19847195/88622506-343be600-d060-11ea-86c5-d0050221b950.png)

**Comment by vadim-bach** [comment]
Changed the field from number to password type. Verified that it now works properly with new app. Pull the latest code and re-open if it still doesn't work.
