### ISSUE TITLE
Add Revision info to groovy code so we know which is which

### ISSUE THREAD

**Issue by fireheadman** [vadim-bach/EyezOn-SmartThings-Switch#4]
I am going back and forth trying to make this work, but after a few days I forget which version I have in the IDE for ST.
Would be nice if there was a revision entry/comment that showed which script was being used.

d

**Comment by jimmyla** [comment]
i need help

**Comment by aftadelian** [comment]
i think i did everything correctly but im getting an error code on line 131.                             
157b716d-2a7e-4012-80cb-3c2bfa9be25c 7:02:25 PM: error java.lang.NullPointerException @line 131 (getSystemStatus).

please help.
thanks

**Comment by vadim-bach** [comment]
Good callout. Added variant # to code.

**Comment by vadim-bach** [comment]
@aftadelian I'm guessing it's because you didn't attach the device using this handler to any Location (e.g. Home). Give it a go and let me know if it's still breaking for you.

**Comment by aftadelian** [comment]
how do i attach the handler (sorry) have no idea what im doing here

**Comment by vadim-bach** [comment]
Go to "My Devices" section in your SmartThings IDE, navigate to the switch(es) you created using this handler, and make sure that Location column is set for them. I'm assuming you already read the instructions about how to make this handler work, especially in regards to setting up the virtual switches.

**Comment by aftadelian** [comment]
oh yes. sorry i misread ur latest post. i have a location set for the devices. i thought you meant i had to set a location for the handler. Also, just an fyi the "execution location" is showing "cloud". not sure if that the correct location.

**Comment by vadim-bach** [comment]
Execution location being "Cloud" is fine. Also can you click into the "Location" and see if Time Zone field is set? Maybe that's the problem then...

**Comment by aftadelian** [comment]
Well, its me again, i appreciate your responses. not sure where i can find the time zone field for the location. im looking at the location where the device is located and i cant see a time zone field which i can edit.

**Comment by vadim-bach** [comment]
<img width="1222" alt="Screen Shot 2020-12-15 at 11 07 15 PM" src="https://user-images.githubusercontent.com/33889138/102304135-b901a080-3f2a-11eb-9b53-e7c1fdec0da4.png">

**Comment by aftadelian** [comment]
Wow, very interesting, i dont have the "coordinates", "time zone" and "weather" on that page. i wonder why that is.

**Comment by vadim-bach** [comment]
That is very strange indeed! I wish I could tell you why but you'd probably need to ask SmartThings support for that. In the meantime though I'll try to see if I can rework the handler code to not require timezone at all as I believe it's used solely for logging.

**Comment by aftadelian** [comment]
ok thanks

**Comment by aftadelian** [comment]
figured it out and got it to work. thanks u very much

**Comment by vadim-bach** [comment]
What exactly did you do? (might be useful for other people who experience a similar issue).
