### ISSUE TITLE
How to make Eyes on disarm switch 

### ISSUE THREAD

**Issue by Beastlynoob** [vadim-bach/EyezOn-SmartThings-Switch#5]
I was able to create the switches for arm and stay but I also wanted to create one for disarming so that in the smart things home monitor when I click disarm it disarms the alarm.

**Comment by vadim-bach** [comment]
If you toggle either of these arm/stay switches to off position it would disarm the alarm for you.

**Comment by vadim-bach** [comment]
Resolving issue seeing as there's no further follow-up. Let me know if there is still an actual issue.
